" zM: foldall
" General: {{{
" remapping the leader key
let mapleader = ","
" }}}
" Source_path_setting: {{{
source ~/.config/nvim/vimfiles/plugin.vim
source ~/.config/nvim/vimfiles/general.vim
" }}}
" GUI Setting: {{{
source ~/.config/nvim/vimfiles/gui.vim
" }}}

" vim: ft=vim foldmethod=marker foldcolumn=1 foldlevelstart=0

